version: 2
jobs:
  unit:
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          LOG_LEVEL: DEBUG
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - run: bundle exec rubocop
  functional:
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          LOG_LEVEL: DEBUG
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:0.10.2.1
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: wurstmeister/kafka:0.10.2.1
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9093
          KAFKA_PORT: 9093
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: wurstmeister/kafka:0.10.2.1
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9094
          KAFKA_PORT: 9094
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec --profile --tag functional spec/functional
workflows:
  version: 2
  test:
    jobs:
      - unit
      - functional
